using Microsoft.CodeAnalysis.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestInheritanceGenerator.Test
{
    [TestClass]
    public class MsTestGeneratorTests : GeneratorTests
    {
        protected override ReferenceAssemblies AddReferenceAssemblies(ReferenceAssemblies input)
        {
            var result = input.AddPackages([new PackageIdentity("MSTest.TestFramework", "3.6.3")]);
            return result;
        }

        protected override string CreateSourceCode(string @namespace, string name, string extraTypeKeywords, bool addSkipInheritanceGenerationAttribute)
        {
            var result = $@"
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace {@namespace}
{{
    [TestClass]
    {(addSkipInheritanceGenerationAttribute ? "[SkipInheritanceGeneration]" : "")}
    public {extraTypeKeywords}class {name}
    {{
    }}
}}";
            return result;
        }

        protected override string CreateGeneratedCode(string namespace1, string namespace2, string name, bool addAttribute)
        {
            var result = $@"
// <auto-generated/>
#pragma warning disable CS1591

namespace {namespace2}
{{
    {(addAttribute ? "[Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute]" : "")}
    public partial class {name} : {namespace1}.{name}
    {{
    }}
}}
";
            return result;
        }
    }
}
